# Generated by Django 4.1.4 on 2023-12-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor_patient_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
    ]
